# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
    unzip -d . gradle-8.0-bin.zip
  displayName: Download Gradle 8.0

- script: |
    ./gradle-8.0/bin/gradle bundleRelease
  displayName: Build Bundle with Gradle 8.0
